### ISSUE TITLE
MD5 Summary does not work on systems with FIPS enabled

### ISSUE THREAD

**Issue by NBP-Lilly** [OceanDataTools/openvdm#52]
Running the md5 summary fails on when FIPS is enabled.

**To Reproduce**
1. On a FIPS enabled openVDM server, click run on "Rebuild MD5 summary" 
2. There is a warning message saying that "Updating MD5 Summary failed" and the worker crashed

**Expected behavior**
Ideally the md5 summary produces no errors.

**Desktop**
 - OS: RHEL 8.10 with FIPS enabled.
 - Kernel: Linux 4.18.0-553.16.1.el8_10.x86_64
 - Python Version: 3.8.17

**Additional context**
The error message for the md5_summary log is as follows:
```
--- Logging error ---
Traceback (most recent call last):
  File "/opt/openvdm/venv/lib64/python3.8/site-packages/python3_gearman/worker.py", line 233, in on_job_execute
    job_result = function_callback(self, current_job)
  File "server/workers/md5_summary.py", line 446, in task_rebuild_md5_summary
    output_results = build_md5_summary_md5(gearman_worker)
  File "server/workers/md5_summary.py", line 120, in build_md5_summary_md5
    md5_summary_md5_file.write(hash_file(gearman_worker.md5_summary_filepath))
  File "server/workers/md5_summary.py", line 74, in hash_file
    raise err
  File "server/workers/md5_summary.py", line 65, in hash_file
    md5 = hashlib.md5()
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

``` 
Having run into this issue before, I believe this is due to how md5 is declared in the following:

https://github.com/OceanDataTools/openvdm/blob/536d068b65acf0cd1fcd40fa6a91196d7e81ffaf/server/workers/md5_summary.py#L65

I was able to fix the issue on our server locally by changing the function declaration to be the following:
```
md5 = hashlib.md5(usedforsecurity=False)
```

This issue and solution can also be seen from local python interpreter output:
```
Python 3.8.17 (default, Aug 10 2023, 12:50:17)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> md5 = hashlib.md5()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
>>> md5 = hashlib.md5(usedforsecurity=False)
>>>
```

**Comment by webbpinner** [comment]
I did my own research and came to the same conclusions however everything I found said that the usedforsecurity=False didn't come until python3.9... I guess stackoverflow is wrong.
May be a little while until i can get around to incorporating this into the main branch.

Also didn't know OpenVDM was in-use on the NBP.  Would be great to get an email from the ship explaining how the ship is using it as well as any question they might have.

**Comment by webbpinner** [comment]
checked in potential fix [0d08080](https://github.com/OceanDataTools/openvdm/commit/0d080802346b70ae59763134ee6644faae58361f)
