### ISSUE TITLE
Problems with initial install

### ISSUE THREAD

**Issue by botheredbybees** [OceanDataTools/openvdm#6]
**Describe the bug**
Hi Webb. I just got back to setting up OpenVDM for the Nuyina and had a bit of a struggle getting the first collection system transfer working. It wouldn't download files from my remote server using SSH, giving the following error in the tail message for the openvdm:run_collection_system_transfer_1 script:

--- Logging error ---
Traceback (most recent call last):
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/worker.py", line 233, in on_job_execute
    job_result = function_callback(self, current_job)
  File "server/workers/run_collection_system_transfer.py", line 994, in task_run_collection_system_transfer
    """
  File "server/workers/run_collection_system_transfer.py", line 391, in build_dest_dir
    'ignoreFilter': gearman_worker.collection_system_transfer['ignoreFilter'].replace('{cruiseID}', gearman_worker.cruise_id).replace('{loweringID}', lowering_id)
TypeError: replace() argument 2 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
    has an 'encoding' attribute, it is used to determine how to do the
  File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
    if self.formatter:
  File "/usr/lib/python3.8/logging/__init__.py", line 664, in format
    time (as determined by a call to usesTime(), formatTime() is
  File "/usr/lib/python3.8/logging/__init__.py", line 369, in getMessage
    arguments with the message.
TypeError: not all arguments converted during string formatting
Call stack:
  File "server/workers/run_collection_system_transfer.py", line 1178, in <module>
    logging.debug("Defining Signal Handlers...")
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/worker.py", line 88, in work
    continue_working = self.poll_connections_until_stopped(
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/connection_manager.py", line 249, in poll_connections_until_stopped
    self.handle_connection_activity(
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/connection_manager.py", line 202, in handle_connection_activity
    self.handle_read(current_connection)
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/connection_manager.py", line 281, in handle_read
    current_handler.fetch_commands()
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/command_handler.py", line 45, in fetch_commands
    continue_working = self.recv_command(cmd_type, **cmd_args)
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/command_handler.py", line 75, in recv_command
    completed_work = cmd_callback(**cmd_args)
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/worker_handler.py", line 182, in recv_job_assign_uniq
    self.connection_manager.on_job_execute(gearman_job)
  File "server/workers/run_collection_system_transfer.py", line 901, in on_job_execute
    self.data_start_date = self.ovdm.get_cruise_start_date() or "1970/01/01 00:00"
  File "/opt/openvdm/venv/lib/python3.8/site-packages/python3_gearman/worker.py", line 235, in on_job_execute
    return self.on_job_exception(current_job, sys.exc_info())
  File "server/workers/run_collection_system_transfer.py", line 916, in on_job_exception
    logging.debug("End date/time filter: %s", self.data_end_date)
Message: <class 'TypeError'>
Arguments: ('worker.py', 233)
2021-08-09 04:26:49,095 ERROR - Job: H:aadc-openvdm:28362, AWS430_barometer transfer failed at: 08/09/21 04:26:49

As you can see there are a couple of things going wrong here, but I didn't drill down far enough to solve them all. 

I did get our transfers working though, but first enabling lowerings, and then adding a lowering record, which seems to have set things going OK for us here. I'm not sure what was going wrong with the debug logging though, or why I needed a lowering record before any file transfers would work.

cheers,
Peter

**Comment by webbpinner** [comment]
I think I found this cause of the debug message failure but still scratching my head as to “how”.

**Comment by webbpinner** [comment]
I think if fixed this awhile back so I'm going to close the ticket.
